import OpenAI from "openai";
import { NextResponse } from "next/server";

/*
 * Lightizer AI knowledge.
 *
 * This tells the assistant who it represents and what information
 * it is allowed to provide about the portfolio.
 */
const LIGHTIZER_CONTEXT = `
You are Lightizer AI, the AI assistant for the Lightizer Technologies portfolio website.

Your purpose is to help visitors learn about Chukwuka Uchenna, his projects,
skills, work and Lightizer Technologies.

ABOUT CHUKWUKA:
- Name: Chukwuka Uchenna.
- He works across software development, data, artificial intelligence and UI/UX.
- He has a background in software programming.
- He is studying Applied Artificial Intelligence.
- He works with Python and JavaScript.
- He is continuously building projects and improving his technical skills.

LIGHTIZER TECHNOLOGIES:
- Lightizer Technologies is a technology and creative space created by Chukwuka.
- It explores software development, artificial intelligence, data and digital experiences.
- Its focus is turning ideas into useful technology.

FEATURED PROJECTS:

1. HumaniTrack AI
- An AI-powered humanitarian aid management system.
- Designed for NGOs and humanitarian organizations.
- Currently under active development.

2. Customer Churn Predictor
- A machine learning project.
- Predicts the likelihood that a customer may churn.
- Built using Python and machine-learning/data-analysis tools.

3. AQI Explorer
- A data analysis project focused on air-quality information.
- Uses Python, Pandas and data analysis/visualization.

OTHER WORK:
- Regression analysis and data-analysis experiments.
- AI and machine-learning learning projects.
- Web development experiments.
- Interactive digital experiences.

AREAS OF INTEREST:
- Artificial Intelligence
- Machine Learning
- Python
- Data Analysis
- Data Visualization
- Frontend Development
- Backend Development
- UI/UX
- Intelligent Systems

BEHAVIOR:
- Be friendly, concise and professional.
- Answer questions about Chukwuka and his portfolio naturally.
- Do not invent projects, employers, qualifications, clients or achievements.
- If information is not available, say that you do not currently have that information.
- When appropriate, encourage visitors to explore the relevant section of the portfolio.
`;

/*
 * POST /api/chat
 *
 * Receives a visitor's question and returns a response
 * generated by Lightizer AI.
 */
export async function POST(request: Request) {
    try {
        /*
         * Read the API key from the server environment.
         *
         * The key stays on the server and is never sent
         * to the visitor's browser.
         */
        const apiKey = process.env.OPENAI_API_KEY;

        /*
         * Check whether Next.js successfully loaded the key.
         *
         * This logs only true/false and never prints the
         * actual secret key.
         */
        console.log(
            "OPENAI_API_KEY loaded:",
            Boolean(apiKey)
        );

        /*
         * Return a proper JSON error if the key is missing.
         */
        if (!apiKey) {
            console.error(
                "Lightizer AI: OPENAI_API_KEY is missing."
            );

            return NextResponse.json(
                {
                    error:
                        "The Lightizer AI server is not configured correctly.",
                },
                {
                    status: 500,
                }
            );
        }

        /*
         * Create the OpenAI client only AFTER confirming
         * that the API key exists.
         *
         * This fixes the previous 'Missing credentials'
         * crash that happened during module loading.
         */
        const openai = new OpenAI({
            apiKey,
        });

        /*
         * Read the JSON sent from LightizerAI.tsx.
         */
        const body = await request.json();

        /*
         * Extract the visitor's message.
         */
        const message = body?.message;

        /*
         * Validate the message before sending anything
         * to the OpenAI API.
         */
        if (
            !message ||
            typeof message !== "string" ||
            !message.trim()
        ) {
            return NextResponse.json(
                {
                    error: "A valid message is required.",
                },
                {
                    status: 400,
                }
            );
        }

        /*
         * Generate the Lightizer AI response.
         *
         * GPT-5.6 Luna is suitable here because this assistant
         * mainly answers short portfolio questions.
         */
        const response = await openai.responses.create({
            model: "gpt-5.6-luna",

            /*
             * Instructions provide the portfolio knowledge
             * and define how Lightizer AI should behave.
             */
            instructions: LIGHTIZER_CONTEXT,

            /*
             * Send the visitor's question to the model.
             */
            input: message.trim(),

            /*
             * Portfolio answers should remain relatively short.
             */
            max_output_tokens: 400,
        });

        /*
         * Extract the generated text.
         */
        const answer = response.output_text;

        /*
         * Make sure we actually received text before
         * returning the response.
         */
        if (!answer) {
            return NextResponse.json(
                {
                    error:
                        "Lightizer AI did not generate a response.",
                },
                {
                    status: 500,
                }
            );
        }

        /*
         * Send the generated answer back to LightizerAI.tsx.
         */
        return NextResponse.json({
            response: answer,
        });
    } catch (error) {
        /*
         * Print the real technical error in the VS Code
         * terminal so we can diagnose problems.
         */
        console.error(
            "Lightizer AI backend error:",
            error
        );

        /*
         * Always return JSON to the frontend.
         *
         * This prevents the previous:
         * 'Unexpected end of JSON input'
         * error.
         */
        return NextResponse.json(
            {
                error:
                    "Lightizer AI could not generate a response.",
            },
            {
                status: 500,
            }
        );
    }
}